# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'masterTime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        # MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # analysis_but
        self.analysis_but = QtWidgets.QPushButton(self.centralwidget)
        self.analysis_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.analysis_but.setGeometry(QtCore.QRect(0, 270, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analysis_but.sizePolicy().hasHeightForWidth())
        self.analysis_but.setSizePolicy(sizePolicy)
        self.analysis_but.setStyleSheet("QPushButton {\n"
"    border: 0;\n"
"    text-align: left;\n"
"    margin-left: 15px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/img/bar-chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.analysis_but.setIcon(icon)
        self.analysis_but.setIconSize(QtCore.QSize(16, 16))
        self.analysis_but.setObjectName("analysis_but")

        # line
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(250, 0, 16, 16777215))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        # instructions_but
        self.instructions_but = QtWidgets.QPushButton(self.centralwidget)
        self.instructions_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instructions_but.setGeometry(QtCore.QRect(0, 320, 241, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructions_but.sizePolicy().hasHeightForWidth())
        self.instructions_but.setSizePolicy(sizePolicy)
        self.instructions_but.setStyleSheet("QPushButton {\n"
"    border: 0;\n"
"    text-align: left;\n"
"    margin-left: 15px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/img/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.instructions_but.setIcon(icon1)
        self.instructions_but.setObjectName("instructions_but")

        # ----- Stacked start -----
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(260, 0, 541, 601))
        self.stackedWidget.setObjectName("stackedWidget")
        # important_urgent_page
        # self.important_urgent_page = QtWidgets.QWidget()
        # self.important_urgent_page.setObjectName("important_urgent_page") # **
        # self.imur_label = QtWidgets.QLabel(self.important_urgent_page)
        # self.imur_label.setGeometry(QtCore.QRect(40, 60, 171, 16))
        # self.imur_label.setObjectName("imur_label")
        # self.stackedWidget.addWidget(self.important_urgent_page) # **
        # important_nuurgent_page
        # self.important_unurgent_page = QtWidgets.QWidget()
        # self.important_unurgent_page.setObjectName("important_unurgent_page") # **
        # self.imunur_label = QtWidgets.QLabel(self.important_unurgent_page)
        # self.imunur_label.setGeometry(QtCore.QRect(70, 70, 191, 21))
        # self.imunur_label.setObjectName("imunur_label")
        # self.stackedWidget.addWidget(self.important_unurgent_page) # **
        # unimportant_urgent_page
        # self.unimportant_urgent_page = QtWidgets.QWidget()
        # self.unimportant_urgent_page.setObjectName("unimportant_urgent_page") # **
        # self.unimur_label = QtWidgets.QLabel(self.unimportant_urgent_page)
        # self.unimur_label.setGeometry(QtCore.QRect(50, 90, 171, 16))
        # self.unimur_label.setObjectName("unimur_label")
        # self.stackedWidget.addWidget(self.unimportant_urgent_page) # **
        # unimportant_unurgent_page
        # self.unimportant_unurgent_page = QtWidgets.QWidget()
        # self.unimportant_unurgent_page.setObjectName("unimportant_unurgent_page") # **
        # self.unimunur_label = QtWidgets.QLabel(self.unimportant_unurgent_page)
        # self.unimunur_label.setGeometry(QtCore.QRect(40, 60, 221, 16))
        # self.unimunur_label.setObjectName("unimunur_label")
        # self.stackedWidget.addWidget(self.unimportant_unurgent_page) # **
        # char_page
        # self.char_page = QtWidgets.QWidget()
        # self.char_page.setObjectName("char_page") # **
        # self.tabWidget = QtWidgets.QTabWidget(self.char_page)
        # self.tabWidget.setGeometry(QtCore.QRect(10, 20, 521, 571))
        # self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        # self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        # self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        # self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        # self.tabWidget.setMovable(False)
        # self.tabWidget.setTabBarAutoHide(False)
        # self.tabWidget.setObjectName("tabWidget")
        # self.day_tab = QtWidgets.QWidget()
        # self.day_tab.setObjectName("day_tab")
        # self.tabWidget.addTab(self.day_tab, "")
        # self.week_tab = QtWidgets.QWidget()
        # self.week_tab.setObjectName("week_tab")
        # self.tabWidget.addTab(self.week_tab, "")
        # self.month_tab = QtWidgets.QWidget()
        # self.month_tab.setObjectName("month_tab")
        # self.tabWidget.addTab(self.month_tab, "")
        # self.year_tab = QtWidgets.QWidget()
        # self.year_tab.setObjectName("year_tab")
        # self.tabWidget.addTab(self.year_tab, "")
        # self.stackedWidget.addWidget(self.char_page) # **
        # instructions_page
        # self.instructions_page = QtWidgets.QWidget()
        # self.instructions_page.setObjectName("instructions_page") # **
        # self.instructions_label = QtWidgets.QLabel(self.instructions_page)
        # self.instructions_label.setGeometry(QtCore.QRect(270, 200, 141, 31))
        # self.instructions_label.setObjectName("instructions_label")
        # self.stackedWidget.addWidget(self.instructions_page) # **
        # ----- Stack end -----

        # im_ur_but
        self.im_ur_but = QtWidgets.QPushButton(self.centralwidget)
        self.im_ur_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.im_ur_but.setGeometry(QtCore.QRect(10, 70, 110, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.im_ur_but.sizePolicy().hasHeightForWidth())
        self.im_ur_but.setSizePolicy(sizePolicy)
        self.im_ur_but.setStyleSheet("QPushButton {\n"
"    background-color: #F2FFE9;\n"
"    border: 0px;\n"
"    border-radius: 5px;\n"
"    margin-bottom:3px;\n"
"}")
        self.im_ur_but.setObjectName("im_ur_but")

        # im_nur_but
        self.im_nur_but = QtWidgets.QPushButton(self.centralwidget)
        self.im_nur_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.im_nur_but.setGeometry(QtCore.QRect(130, 70, 110, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.im_nur_but.sizePolicy().hasHeightForWidth())
        self.im_nur_but.setSizePolicy(sizePolicy)
        self.im_nur_but.setStyleSheet("QPushButton {\n"
"    background-color: #F2FFE9;\n"
"    border: 0px;\n"
"    border-radius: 5px;\n"
"    margin-bottom:3px;\n"
"}")
        self.im_nur_but.setObjectName("im_nur_but")

        # nim_ur_but
        self.nim_ur_but = QtWidgets.QPushButton(self.centralwidget)
        self.nim_ur_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nim_ur_but.setGeometry(QtCore.QRect(10, 150, 110, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.nim_ur_but.sizePolicy().hasHeightForWidth())
        self.nim_ur_but.setSizePolicy(sizePolicy)
        self.nim_ur_but.setStyleSheet("QPushButton {\n"
"    background-color: #F2FFE9;\n"
"    border: 0px;\n"
"    border-radius: 5px;\n"
"    margin-top:3px;\n"
"}")
        self.nim_ur_but.setObjectName("nim_ur_but")

        # nim_nur_but
        self.nim_nur_but = QtWidgets.QPushButton(self.centralwidget)
        self.nim_nur_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nim_nur_but.setGeometry(QtCore.QRect(130, 150, 110, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(50)
        sizePolicy.setHeightForWidth(self.nim_nur_but.sizePolicy().hasHeightForWidth())
        self.nim_nur_but.setSizePolicy(sizePolicy)
        self.nim_nur_but.setStyleSheet("QPushButton {\n"
"    background-color: #F2FFE9;\n"
"    border: 0px;\n"
"    border-radius: 5px;\n"
"    margin-top:3px;\n"
"}")
        self.nim_nur_but.setObjectName("nim_nur_but")

        # refresh_but
        self.refresh_but = QtWidgets.QPushButton(self.centralwidget)
        self.refresh_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.refresh_but.setGeometry(QtCore.QRect(20, 540, 35, 35))
        self.refresh_but.setStyleSheet("QPushButton{\n"
"    border: 5px black solid;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"}")
        self.refresh_but.setText("R")
        # icon2 = QtGui.QIcon()
        # icon2.addPixmap(QtGui.QPixmap(":/newPrefix/img/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.reset_but.setIcon(icon2)
        self.refresh_but.setObjectName("refresh_but")

        # add_but
        self.add_but = QtWidgets.QPushButton(self.centralwidget)
        self.add_but.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_but.setGeometry(QtCore.QRect(80, 540, 35, 35))
        self.add_but.setStyleSheet("QPushButton{\n"
"    border: 2px black solid;\n"
"    border-radius: 3px;\n"
"    background-color: white;\n"
"}")
        self.add_but.setText("+")
        # icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap(":/newPrefix/img/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.add_but.setIcon(icon3)
        self.add_but.setObjectName("add_but")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        # self.stackedWidget.setCurrentIndex(0)
        # self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Time Master"))
        self.analysis_but.setText(_translate("MainWindow", "Analysis"))
        self.instructions_but.setText(_translate("MainWindow", "Instructions"))
        # self.imur_label.setText(_translate("MainWindow", "Important & Urgent"))
        # self.imunur_label.setText(_translate("MainWindow", "Important but not urgnet"))
        # self.unimur_label.setText(_translate("MainWindow", "Not important but urgent"))
        # self.unimunur_label.setText(_translate("MainWindow", "Not important & not urgent"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.day_tab), _translate("MainWindow", "Day"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.week_tab), _translate("MainWindow", "Week"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.month_tab), _translate("MainWindow", "Month"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.year_tab), _translate("MainWindow", "Year"))
        # self.instructions_label.setText(_translate("MainWindow", "Instructions"))
        self.im_ur_but.setText(_translate("MainWindow", "Important\n"
"Urgent"))
        self.im_nur_but.setText(_translate("MainWindow", "Important\n"
"Not urgent"))
        self.nim_ur_but.setText(_translate("MainWindow", "Not important\n"
"Urgent"))
        self.nim_nur_but.setText(_translate("MainWindow", "Not important\n"
"Not urgent"))
import Chart_rc
